on:
  push:
    branches:
    - master


jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: 设置 Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: 安装依赖
      run: npm install
    - name: 打包软件
      run: npm run build
    - name: 上传
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "./dist/*"
        target: /www/wwwroot/actions.h5.run
