on:
  push:
    branches:
    - master


jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: npm install
    - name: build software
      run: npm run build
    - name: upload
      uses: appleboy/scp-action@v0.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "dist"
        target: /www/wwwroot/actions.h5.run
